version: '3.8'

services:
  nextcloud_app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - ./data:/var/www/html
    environment:
      TZ: Europe/Paris
      NEXTCLOUD_TRUSTED_DOMAINS: test.luchier.fr
      TRUSTED_PROXIES: test.luchier.fr
      OVERWRITECLIURL: https://test.luchier.fr
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: test.luchier.fr
